---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valheim
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alimansoor1/k8s-cluster.git
    targetRevision: main
    path: apps/valheim/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: valheim
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
