apiVersion: v1
kind: Service
metadata:
  name: valheim-world-1
  namespace: valheim
spec:
  type: NodePort
  selector:
    app: valheim-world-1
  ports:
    - name: game
      protocol: UDP
      port: 2456
      targetPort: 2456
      nodePort: 32456
    - name: game-1
      protocol: UDP
      port: 2457
      targetPort: 2457
      nodePort: 32457
    - name: game-2
      protocol: UDP
      port: 2458
      targetPort: 2458
      nodePort: 32458
