---
apiVersion: v1
kind: Namespace
metadata:
  name: valheim
  labels:
    app.kubernetes.io/part-of: valheim
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
