---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-config
  namespace: valheim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3
