---
apiVersion: v1
kind: Service
metadata:
  name: valheim-server
  namespace: valheim
spec:
  type: NodePort
  selector:
    app: valheim
  ports:
  - name: game-udp
    port: 2456
    targetPort: 2456
    protocol: UDP
    nodePort: 32456
  - name: query-udp
    port: 2457
    targetPort: 2457
    protocol: UDP
    nodePort: 32457
  - name: query-tcp
    port: 2458
    targetPort: 2458
    protocol: TCP
    nodePort: 32458
