cluster:
  aggregatorCA:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYakNDQVFXZ0F3SUJBZ0lRT3BWM0NRUEdHaVNiRXhTZWZzekkyakFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMk1EY3dNVEV3TkRJeE5Gb1hEVE0yTURZeU9ERXdOREl4TkZvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSFZGZjlhZ0xWVWVOcnhrZVgvM2ljeGpkcmhKQ2FvOUdKcFYxTmhMVDYyVUpoSWxLaGJ2CmUwQ0NQV3BrK0tsN21BdmdrSVhtTjh0ai8raytFUTNzWlFTallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVHY0FYdDAxSnVKb1dROHhuRGoxd0JPUmxnazR3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnCldYUGRyNERUcGdCMG1CNWhHY2dUZldHVFdZUmhCblpiMXE4OWZjV0VodUFDSUh1YTYyanp5cUZESjN2QXAzNFIKY1VqYTZpaUllZG9MeDZQVzA3VG1LZ1F5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUFkcXNmTDRkd3Z6WU1zekRGVlBwSndFWExTUHJQTmk2L09iMUVhSlR0OVVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZFVWLzFxQXRWUjQydkdSNWYvZUp6R04ydUVrSnFqMFltbFhVMkV0UHJaUW1FaVVxRnU5NwpRSUk5YW1UNHFYdVlDK0NRaGVZM3kyUC82VDRSRGV4bEJBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  apiServer:
    admissionControl:
    - configuration:
        apiVersion: pod-security.admission.config.k8s.io/v1alpha1
        defaults:
          audit: restricted
          audit-version: latest
          enforce: baseline
          enforce-version: latest
          warn: restricted
          warn-version: latest
        exemptions:
          namespaces:
          - kube-system
          runtimeClasses: []
          usernames: []
        kind: PodSecurityConfiguration
      name: PodSecurity
    auditPolicy:
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
      - level: Metadata
    image: registry.k8s.io/kube-apiserver:v1.36.2
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUxhRktQbW9RN1N5VEhCWlZyYmxFdHd3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakEzTURFeE1EUXlNVFJhRncwek5qQTJNamd4TURReQpNVFJhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVJlTk1tc0Q4VGxHd042c2ViOW9ObkxmSVN4RzIvc25xZ3ZYUnRsTGRRclZta09XanE2aHIyWnlmdG4KL3pPVFFrM2FRVTNzRm5NQm1qcnlOWG94L21GZG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGS05OVERNTUthaUc3WWUxL1NlV3pVa3hFOHFlTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUJReFJ1QmwKb1pwdmhqekFWVWRkZnpVckhkdTJDVFlpb2lIZGFTQ3lQUDEzQWlFQXpXdmtVWjJpN2NIRURaOFU2NDZtR1pjegpuRzRScDAzZmNWWVR2TkVOU1NjPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZuTENGbmhpd21hWGFDYzB4Ymp6MEFsa1FDR0NTNkl1MlYxK0huU2RBUmNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWGpUSnJBL0U1UnNEZXJIbS9hRFp5M3lFc1J0djdKNm9MMTBiWlMzVUsxWnBEbG82dW9hOQptY243Wi84emswSk4ya0ZON0JaekFabzY4alY2TWY1aFhRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  clusterName: valheim
  controlPlane:
    endpoint: https://52.220.151.154:6443
  controllerManager:
    image: registry.k8s.io/kube-controller-manager:v1.36.2
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
  etcd:
    ca:
      crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmakNDQVNTZ0F3SUJBZ0lSQUo3RHJ5dXpYaUR5UDZCZDlZcnlPVGt3Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TmpBM01ERXhNRFF5TVRSYUZ3MHpOakEyTWpneE1EUXlNVFJhTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTaDRkVHU4bDR4Cks3RjlwZThtMzE5OTZsbHREQzQ1ejB3Z1J3V1pseGdFaXVQcWE1S25kcHRTOXIyNUtBR3o3YVNBTU5qY2kxUmIKUWJtQVNNR3RqWVY1bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRlBhU2gzVXNTcmRrCkp5Ym1rUGZwYzZNaHpJTGRNQW9HQ0NxR1NNNDlCQU1DQTBnQU1FVUNJUURjT0tNS2t1RVhTd0RGT0o2b0c0d1IKU0lFamxLOHE1cU1JUFFXUkd0K0NLd0lnZUJRRmdVYVFsaFpxdjcrRDdhOEhKR1hxdzNFRzJSYStPcFZpVm1XZgp2Mk09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1zTWgzZFluQ2VHNGE0VEszZUNNNWpOZDY3Q3NXb2lDaGlhMkVHYmJiR0FvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFb2VIVTd2SmVNU3V4ZmFYdkp0OWZmZXBaYlF3dU9jOU1JRWNGbVpjWUJJcmo2bXVTcDNhYgpVdmE5dVNnQnMrMmtnRERZM0l0VVcwRzVnRWpCclkyRmVRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  extraManifests: []
  id: jk447IUH_N24ojZ1OPxYOoWV5UD6wtaJkslzQQ3ax2A=
  inlineManifests: []
  network:
    dnsDomain: cluster.local
    podSubnets:
    - 10.244.0.0/16
    serviceSubnets:
    - 10.96.0.0/12
  proxy:
    image: registry.k8s.io/kube-proxy:v1.36.2
  scheduler:
    image: registry.k8s.io/kube-scheduler:v1.36.2
  secret: mz7AGwgRcpfUq8RISs2j8+DhYTaz0p4IuJI9Y9jqRao=
  secretboxEncryptionSecret: nHzdAYoIEH4FAN16fgQi5NCh9TlaKzkL5Zcn6rjVeg4=
  serviceAccount:
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKSndJQkFBS0NBZ0VBeDFkK212S0hmSzJvYng3Zm45T2pJSkF6bW5XOXgrU0paZ1JCSWlyNFdqMU1tOEthCkl3NnVXM1NCblR3MEwrckJ6T0hwRzZHRkpKTzFlM2QrNG03M0ZUcDdSVjB3MlJJQWlYazdwYjFoUmZNaEVGY3YKTGZJTVdzekpwZU9xTGZPS2tTL3c1QWh3KzdGNWYydFZYbHpCQ3d5bFU4TmR3enloKzVTdXhKcTBZQlRjdGlrMQoxRTJ1NDZIRUhxZzhFb01BVWVoSkJ1am05Mmd1eTVUeWdBYk5iNU1vNlVDdVhCMllYQjJsQ2trdGdHcWZ1QXZsCkgwUXpoVUo1elZwWVhSNWZKQlhVdEROMlVYWVY0Y0RaSDcwL1B5aER0SzA4eElaMXhGRkl6eXcydzN5WEwvWmwKMnlZWmhaU2hrbjdZVEtTeUlMeTlMZW8raHNxVG43YWFraXNMZXlNVEthNFovRWh0dmhROGd3a3I4M0x0TXdscwpDRGQxb1RZZ2NnUGNGSXhrZVhoZklPcTU4b3BzUER2dVFGZ2xvc1Ird0g4OGwrQzJzbUdKVUxUdkVlY1NkQ05hCmZzcm9hWUY3UWlvWTRkR2pqbXpYWmx3NmNXUUVzTi9CN1NYZUhzQlRwQ0FlOTZDK3NEZ2xMTHZlNFBxYkQ3STYKV05CTkxBN3Z5RXhjVUU5TGdsRU9TZWk5bDUzQmNLVkxnNTNmbnpRRGt5cHh5Y3BjUjlpa212aDdGMVYyZSt0TwpDY1NOY21CTTNJUlcwSnQxWFVXQWtsMVQwRHU2M0pmOGt4QWp1SmNnOXBxdEpMSmRUdFNqRXpoaGdraUhuY0tnCjB4WXBQRUNjQ244TlJsU2FDNk5pckZVejNPNUpwbzZaTVZ6cmR2YStibmJPZ3VtUy9kOTFRaWVZSXZjQ0F3RUEKQVFLQ0FnQWRIcEZlaGg0M250Q1RodkdJMGV3cTloV3JzeFpwakY5cjJTUkFud0ZQZ1ZQZkR3TGdLeVZhTTc4NQpYbEdMVEdKS0VSZ3gwcHIxK0dQUzZPWk9vb0lTaGt2Nm1uM252OEwzVWcvZUNyZWFkY1UzTTEwdmU0UEZnZFBWCkdWaERSU2ZSUkswT1NwTmltUTdVQjdSZFIvUmxMbEE2VjdnckxJREhGUFdndjY2b3VITnpZcnE3ekN0SGtscHAKVmc4TWJ6bU5QWDdwZFAxRVYrSTZHQVNDb2p2QldFQnFMbW9xQjZLNWxoVUZWeUkvOTVOa1djeDdFRVhzYWdVTAo4KzRqa0N1NnhEdWhwVURiN29HTXpGU0xWK1JVMEFkdjdieUtRdEFTUVFOL1RBaWw3dDNSQWsvbnZ2Mk1iMlZZCjFwRzNSSG5HNFh0TEtVUkFBWGltSkpFWTJCUGhndjhwODZCa2FVd0c4U1pSV2l6ZzJJa0hvOE1tdGNqMjNOaWQKbzBFTGNSV0FIdkR0NHRLb2lOdlVlNlQyR2I4M2dEQWhpTTZXcXh1NlNPUTgzVmhCRkJjc2dXMlV6RUpNSDE0MQpUb3BOcEYwbkZlWWp6Q0VhdXV3dmZTYng4K2NPUVNmdURsU08xNldkd1ZwUXFwUjZDV0VjUG14NWdvS0xpVEpSCkN6YUlBRTM0eEkrUlVtVkhuRmtpd2RvdTdTaUdML1kvZFd1UjlneG1LOVFOMkVDNnlsQmI5SnNqSnQvV1lJQjcKSm1GU0EyVnNxNmNHc0xsZGd1c0NjNjVKZ1ZlY3pXR2I5dTZSSC9zbENIT1FSTC91TXo4bHF2citSb3ptM1U0VQo5anAwZ3hwdURmOSt4V2YxK2R2YmRZZDRmWFBkczY5TjA3R0x1dUhWeXRvRE1UUmIzUUtDQVFFQS8rcnFQWjdnCjBOYzcvV2lCb1RkYlNvU3c2VnY0Z1hjOHhJUmVzcEcremIrWklTOHRiQ1NkQ0RjNW55ejZZemFHS05iRDRwcTYKeGdGK2tLblNoQWNoMG0vMDhsRVF4NEE5aXJxMTFXOENyKzFaNUFMaW9TRkJGQTUvY0RidE5kSitqSmlSZ1hGUgpsNW1WVDI0Q0NJY0FZVVc4WkRRRUQvdnBEbnN4RWpTMXhtc1NHL3dCelVVemR6YnFiTmZMKy82bkVaMEVkeUpLCnpMMXZrT2p2NkI0WjNjUHBPUHVHeXoxd1NsSWlMUWVHMThKU3JlSUU5d05hNDFPL3I3MXRTeExUSVBNTWhUOFQKMzU5Z016Q3M0Zzc2eXBza1ZnTjNDVHo1SHZmdERSbUlPbTFJK2hhSEdFeTVRbWpOWFNxWm9HMmswNWtaRGZXQwp2aDJxZnVuUUJDMXpTd0tDQVFFQXgyZnJGQ25lWXdheEE1VFlMQ1RwOGllMklLN3cwR0hFOS9mQmNSRUp5UERRClZvUjRGSlUzcmQxUnE5YU5XU21JZCtNazVlWGRpay9mU1RzNEpHTm1rbU4wSGthc09yUWxCVEpQbFVQL3RlTGcKWk9saFdVaktZSDFVR0lFa29UTnN2MnNJWmVSUW01Y2RveXpNTTlkQXBDakZ3TTFxYk1DQU95UXdaVmFzcnJjWQplSTR2MC9NOG4reEZkSlJmbElYeTVNUDZPQ3Q2MUZMVVExZDBJWG1rTVh5RitCS0hNdFRqWkY5MzlpWWpMQkd6CmJmcXFCTWJpdTZtelFCOTBnUEVFajV5bW5jck0yUDN5MEI2clgyd1V4VDZqQUplYWdHL2hrNXhGM2xIMHpGLzkKcmZMdW1LdUdTNHpaR2ovNFhYV3Ntd3pNaG0wUWs3Uk82QTZzY0s2WGhRS0NBUUFmeWtHd3grU3JiS0V5R0dKSgo4WU53blUwUW4vRWR1LzhiZGtvQktxT21FVS9uVkdIekZoVS9xUVNLWmw3d0poekNRL052V2NNcng1RytUS291CjVtZm9LU29uVTdTZTQ2cEJhbkllQWowMk4yaThMek9SeW55NERoajhpb1lxOG12djhSL2FFWWFPSzNEbHZnZVkKb1pTRmdORW5MV0wzelZZbEMxNk1JV29YTE1QQ0lDcmxJZHlEeVptVFRiYzBKVzBCZmh6STQ4U2c3RU5Jbi9iMQpRWS83QVZRZVZQaG9sTWczSXo3Rmt6TEg2SWEydk9YYS9WcXo5SHBTVFZpZlE4WmdTSERjdUhveWhDekNEeURhCnIvdXRZVnBCS1FzSFpjQ1lmVG5BTDlUQlZVUUVkUG54SmM2NWxpVTBsbzhnNDUzZS94eWlwRVhLY2dyMDJ2eVIKR0VoREFvSUJBQXBTRnBpMGtnNE9DcHRrMk10d0hhdXE0b0pPaTZnOVp6UnVYbFM3elFYWmNPOEpiQzJraTMwMApOMFh0bE9OSWd3ZXhlZmRzTGtzNlZ4UXpQSFNsc0dsalBGOVV5UlZBdmFuSE1OZEk3Yk04U3VEdU0xdXJxTTNWCnJzU1Y2bzl0V2ZPT1ZxRHZjRHlkVmF0Y1pqVklycy9RVEd2dU5kUHJJcmZzNTVSWEtCamk0U0ZjT3AxOXVXV04KbFFxem96N01zQVduSHd4Sk05Skpkek1GRTcybnpoZkJtaTE4eUFLWmdpdHZ4WVczODVvVVVIVWd4Q3Y3SDBFWApSMi9LTVAxN2ZBRHkycXpRRWtvbzJxaHE3ZlBDWkZEUkxSNmF1aVJycGdFOTFWL3NYZjgxK0t0SUo1RS9UM1FaCmxpTUZySlVwd2dWRVpGR1EwNHJSaWtQNGZuUldsUUVDZ2dFQUdJcFFWeVZuZWlHemZRN1hBUGhuOU5lazZDY24Kanp0Qm5JYURiWTB1RUp6ak0reXk0Zy9WcXJkcHBQUkZCQXV1OUdRRzdxZERHTmFwakVaVGMzbHhPaEJXUUNoUwpzaVBPdEIxODNyVE1jRVFhdHJ3TWNQSWpBNTV5RkJaQzJsU1NXZHJrcHpqTzhmbkU3b0FNYWk5MFdodnpHbkd0CnhQeTFhbmVQOXdid0FodTh0b1BTZVFETGJxSXhSR2RhT0pCYlFlbHUrbllJWExybFMrV0gxaVg2V0NHYmwxK1EKY1VlTm1tbkdqNlVWZS8wWVVIdXlrUTNSNWt6RGhvUEFqK2wxcjkyY1dKaElvNXlTazdLNE9zQ3JVNTZZaVIrSApwYzVibkoxWTZFV3RBaGZ0K0psd1Q1SEhzMk01aEpNd0ZjMlIrT2k3RTRiL2x0eTFySitoVlpkbktBPT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  token: ibhppp.3rwk4ymbxrn0sd2i
debug: false
machine:
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEE0Mk54L2dMcEJpZjl2b1VabHNUcFdNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQTNNREV4TURReU1UUmFGdzB6TmpBMk1qZ3hNRFF5TVRSYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBTjA2UldTYnhlU3J1U08zUkFPUDlxQXErdEZ5cDVBNDhmblhPCkc3aGg3S3VqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVdGJHS0pzeURWNTJBeUdsRApyYmhET0k2Q2Zid3dCUVlESzJWd0EwRUE4WTJBYzhOV1IxTjZzYy9EV3F1dmN0UmlXMStGM21IN3IvVEU3NUUyClNDR1RLOThqT29WUEd4VFl1UG0yWVpkZjNkRXU3dXN5NUtXc2FqVDdlaVVpQ1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJTk9RbWhaNE9tSmJZQkNaaEhiaFhRSWhIMmhmNXp5enRBK3lyU1lvSllPTgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
  certSANs:
  - 52.220.151.154
  - 10.0.1.165
  features:
    diskQuotaSupport: true
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
    kubePrism:
      enabled: true
      port: 7445
  install:
    disk: /dev/sda
    grubUseUKICmdline: true
    image: ghcr.io/siderolabs/installer:v1.13.5
    wipe: false
  kubelet:
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    image: ghcr.io/siderolabs/kubelet:v1.36.2
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers: ''
  token: 4fmx4l.15zvogl7saaug47c
  type: controlplane
persist: true
version: v1alpha1
---
apiVersion: v1alpha1
auto: stable
kind: HostnameConfig
